Description: Configuration for CANoe participant for SIL Kit Adapter QEMU (chardev) demo
Middleware:
  RegistryUri: silkit://172.25.54.174:8501
# Logging:
  # Sinks:
  # - Type: File
    # Level: Trace
    # LogName: TraceLogFile
